name: Generate Snake Animation

on:
  schedule:
    # Executa todo dia à meia-noite UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar Snake de Contribuições
        uses: Platane/snk@v3
        with:
          github_user_name: c0deby4g4th4
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg

      - name: Commit e push dos arquivos gerados
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Atualizando Snake animation"
          add: "dist/*.svg"
